config/routes.rb
Reservation::Application.routes.draw do
  resources :pilots do
	resources :reservations
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :pilot
  attr_accessible :end, :start
end

app/models/pilot.rb
class Pilot < ActiveRecord::Base
  attr_accessible :license, :name
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  # GET /pilots
  # GET /pilots.json
  def index
    @pilots = Pilot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pilots }
    end
  end

  # GET /pilots/1
  # GET /pilots/1.json
  def show
    @pilot = Pilot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @pilot }
    end
  end

  # GET /pilots/new
  # GET /pilots/new.json
  def new
    @pilot = Pilot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @pilot }
    end
  end

  # GET /pilots/1/edit
  def edit
    @pilot = Pilot.find(params[:id])
  end

  # POST /pilots
  # POST /pilots.json
  def create
    @pilot = Pilot.new(params[:pilot])

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, :notice => 'Pilot was successfully created.' }
        format.json { render :json => @pilot, :status => :created, :location => @pilot }
      else
        format.html { render :action => "new" }
        format.json { render :json => @pilot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pilots/1
  # PUT /pilots/1.json
  def update
    @pilot = Pilot.find(params[:id])

    respond_to do |format|
      if @pilot.update_attributes(params[:pilot])
        format.html { redirect_to @pilot, :notice => 'Pilot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @pilot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1
  # DELETE /pilots/1.json
  def destroy
    @pilot = Pilot.find(params[:id])
    @pilot.destroy

    respond_to do |format|
      format.html { redirect_to pilots_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "My pilots", pilots_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pilots/_form.html.erb
<%= form_for(@pilot) do |f| %>
  <% if @pilot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
      <% @pilot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :license %><br />
    <%= f.text_field :license %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pilots/edit.html.erb
<h1>Editing pilot</h1>

<%= render 'form' %>

<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilots_path %>

app/views/pilots/index.html.erb
<h1>Listing pilots</h1>

<table>
  <tr>
    <th>Name</th>
    <th>License</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pilots.each do |pilot| %>
  <tr>
    <td><%= pilot.name %></td>
    <td><%= pilot.license %></td>
    <td><%= link_to 'Show', pilot %></td>
    <td><%= link_to 'Edit', edit_pilot_path(pilot) %></td>
    <td><%= link_to 'Destroy', pilot, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pilot', new_pilot_path %>

app/views/pilots/new.html.erb
<h1>New pilot</h1>

<%= render 'form' %>

<%= link_to 'Back', pilots_path %>

app/views/pilots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pilot.name %>
</p>

<p>
  <b>License:</b>
  <%= @pilot.license %>
</p>


<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>